# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

scale_factor = 1.15
theme = "tomorrow-night"

[font]
family = "Monaco"

[buffer.nickname]
alignment = "right"

[servers.slashnet]
nickname = "dmd/slashnet"
server = "eco.3e.org"
port = 7777
password_file = "/Users/dmd/Library/Application Support/halloy/slashnet_password"

[servers.undernet]
nickname = "dmd"
server = "irc.undernet.org"
port = 6667
use_tls = false
