# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

scale_factor = 1.15
theme = "dracula"

[font]
family = "Monaco"

[sidebar]
position = "top"

# vim keybindings so option-left/right work on mac
[keyboard]
move_up = "alt+k"
move_down = "alt+j"
move_left = "alt+h"
move_right = "alt+l"

[buffer.nickname]
alignment = "right"
show_access_levels = false

[buffer.server_messages.join]
smart = 1800

[buffer.server_messages.part]
smart = 1800

[buffer.server_messages.quit]
smart = 1800

[servers.slashnet]
nickname = "dmd/slashnet"
server = "eco.3e.org"
port = 7777
password_file = "znc_password"
